# Generated by Django 6.0.1 on 2026-01-30 13:12

import django.core.validators
import images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to=images.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])], verbose_name='Файл изображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('size', models.IntegerField(default=0, verbose_name='Размер файла (в байтах)')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина изображения')),
                ('height', models.IntegerField(default=0, verbose_name='Высота изображения')),
                ('format', models.CharField(default='', max_length=10, verbose_name='Формат файла')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
